const movies = [
    {
        id: '1',
        title: 'Oceans 8',
        category: 'Comedy',
        likes: 4,
        dislikes: 1,
        banner: './img/oceaneight.jpg',
    }, {
        id: '2',
        title: 'Midnight Sun',
        category: 'Comedy',
        likes: 2,
        dislikes: 0,
        banner: './img/midnightsun.jpg',
    }, {
        id: '3',
        title: 'Les indestructibles 2',
        category: 'Animation',
        likes: 3,
        dislikes: 1,
        banner: './img/indestructibles2.jpg',
    }, {
        id: '4',
        title: 'Sans un bruit',
        category: 'Thriller',
        likes: 6,
        dislikes: 6,
        banner: './img/sansunbruit.jpg',
    }, {
        id: '5',
        title: 'Creed II',
        category: 'Drame',
        likes: 16,
        dislikes: 2,
        banner: './img/creed2.jpg',
    }, {
        id: '6',
        title: 'Pulp Fiction',
        category: 'Thriller',
        likes: 11,
        dislikes: 3,
        banner: './img/pulpfictioncartoon.jpg',
    }, {
        id: '7',
        title: 'Pulp Fiction',
        category: 'Thriller',
        likes: 12333,
        dislikes: 32,
        banner: './img/pulpfiction.jpg',
    }, {
        id: '8',
        title: 'Seven',
        category: 'Thriller',
        likes: 2,
        dislikes: 1,
        banner: './img/seven.jpeg',
    }, {
        id: '9',
        title: 'Inception',
        category: 'Thriller',
        likes: 2,
        dislikes: 1,
        banner: './img/inception.jpeg',
    }, {
        id: '10',
        title: 'Gone Girl',
        category: 'Thriller',
        likes: 22,
        dislikes: 12,
        banner: './img/gonegirl.jpeg',
    }, {
        id: '11',
        title: 'Dany The Dog',
        category: 'Action',
        likes: 22,
        dislikes: 30,
        banner: './img/danny.jpg',
    },
    {
        id: '12',
        title: 'Conjuring',
        category: 'Horreur',
        likes: 100,
        dislikes: 0,
        banner: './img/conjuring.jpg',
    },
    {
        id: '12',
        title: 'Ozark',
        category: 'Horreur',
        likes: 2422,
        dislikes: 124,
        banner: './img/ozark.jpg',
    },
]

export const movies$ = new Promise((resolve, reject) => setTimeout(resolve, 100, movies))